### ISSUE TITLE
Adding gitmoji as convention

### ISSUE THREAD

**Issue by bengeois** [Berkmann18/commit-conv#33]
## Proposal
What do you think about adding gitmoji as convention type (https://gitmoji.dev/)
I can work on this if you want.

## Motivation
Lots of repositories are now using gitmoji for their commits

## Use cases and examples
All-contributors bot is using commit-conv to generate commit-message

**Comment by Berkmann18** [comment]
That seems like a good idea to me. Feel free to open a PR for it.
